trigger:
  - main

pool:
  vmImage: 'windows-latest'
#  name: local

variables: {}

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'docker-hub'
    repository: 'junioraraujo/unyleya_projeto_cicd_valdecy'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
